language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - chmod +x TrelloAPIRunner.sh

script:
  - newman run Trello.postman_collection.json --global-var "trelloKey=$trelloKey" --global-var "trelloToken=$trelloToken"  -e Trello.postman_environment.json -r cli,junit -- reporter-junit-export-test-results/junit-results.xml

